version: "3"
services:
  app:
    build: ./
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - API_KEYS=AIzaSyDwlGfRiwh3nKT6ACT_DECyNZ_f30dLTqE,AIzaSyAgDxkNhAocA9MEAQNWUGJEOKOeOjBDhpQ,AIzaSyCVHdFDDkcPWyruAK_5qmHDNBIbZc3r7x4
      - MONGO_URI=mongodb+srv://antstack:antstack@cluster0-xqfmo.mongodb.net/antstack?retryWrites=true&w=majority 
    command:
      sh -c 'npm i && npm start'
