version: "3"
services:
  app:
    build: ./
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - API_KEYS=
      - MONGO_URI=
    command:
      sh -c 'npm i && npm start'
